version: '3.7'
services:
    postgres:
        image: postgres:11.12   
        environment: 
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        ports:
          - '5455:5432'
        volumes:
          - ./postgres/base.sql:/docker-entrypoint-initdb.d/base.sql
    ################################################################
    hahnair:
        build: ./hahnair
        hostname: hahnair
        ports:
          - 8000:8000
          depends_on:
            - postgres
