CREATE TABLE IF NOT EXISTS cards_info (
   card_id                SERIAL PRIMARY KEY,
   card_number            INT,
   card_holder_name       VARCHAR(64),
   car_type               VARCHAR(64),
   card_expiry_date_month INT,
   card_expiry_date_year  INT,
   address1               VARCHAR(256),
   address2               VARCHAR(256),
   address3               VARCHAR(256),
   postal_code            VARCHAR(128),
   city                   VARCHAR(64),
   holder_state           VARCHAR(64),
   country_code           VARCHAR(16),
);